#!/usr/bin/env python

import sys

data = open(sys.argv[1], 'rb').read()

# # pad to fit ROM fully
# if len(data) < romsize:
#     data = data + (romsize - len(data)) * chr(0xff)

print "@0000"

while data != '':
    line = data[:16]
    data = data[16:]

    print ' '.join('%02X' % ord(byte) for byte in line)
