#!/usr/bin/env python

import sys, time

try:
    data = open(sys.argv[1], 'rb').read()
    addr = int(sys.argv[2], 16)
    start_addr = addr
    run_addr = addr
    count = 0

    if len(sys.argv) >= 4:
        port = open(sys.argv[3], 'w')
    else:
        port = None

    if len(sys.argv) >= 5:
        run_addr = int(sys.argv[4], 16)
except:
    print "%s filename addr [ttyport] [runaddr]" % (sys.argv[0],)
    sys.exit(1)

while data != '':
    line = data[:16]
    data = data[16:]

    cmd = "@wm %04x %s" % (addr, ' '.join('%02X' % ord(byte) for byte in line))
    addr += len(line)
    count += len(line)

    print cmd
    if port:
        port.write(cmd + '\n')
        # sleep not necessary with deep FIFO
        # time.sleep((len(cmd) + 12) * 1.0/10000.)

if port:
    port.write("run %04x" % run_addr)

sys.stderr.write("Loaded %d bytes from 0x%04x to 0x%04x (%d x 256 byte pages)\n" % (count, start_addr, addr, (count+255)//256))
