#!/usr/bin/env python

import sys
import time

input = open(sys.argv[1], 'rb')
port = open(sys.argv[2], 'w')

sent = 0
while True:
    data = input.read(128)
    if data == '':
        break
    tx = ''.join('%02X' % ord(char) for char in data)
    port.write('@') # framing byte
    port.write(tx)
    port.flush()
    time.sleep(float(len(tx)+32) / 11000.)

port.write('!')
